const actiontypes = {
  AUTHENTICATE: 'AUTHENTICATE',
  AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',
  AUTHENTICATE_FAILED: 'AUTHENTICATE_FAILED',

  START_WALLET_FETCH: 'START_WALLET_FETCH',
  LOAD_CURRENCIES: 'LOAD_CURRENCIES',
  ADD_EXPENSE: 'ADD_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
};

export default actiontypes;
