const actiontypes = {
  AUTHENTICATE: 'AUTHENTICATE',
  AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',
  AUTHENTICATE_FAILED: 'AUTHENTICATE_FAILED',

  START_WALLET_FETCH: 'START_WALLET_FETCH',
  LOAD_CURRENCIES_SUCCESS: 'LOAD_CURRENCIES_SUCCESS',
  LOAD_CURRENCIES_FAILED: 'LOAD_CURRENCIES_FAILED',
  ADD_EXPENSE_SUCCESS: 'ADD_EXPENSE',
  ADD_EXPENSE_FAILED: 'ADD_EXPENSE_FAILED',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
};

export default actiontypes;
